version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: riya@root
      MYSQL_DATABASE: plant
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./plant.sql:/docker-entrypoint-initdb.d/plant.sql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: backend-image
    container_name: backend_container
    ports:
      - "8085:8085"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/plant?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: riya@root
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    image: frontend-image
    container_name: frontend_container
    ports:
      - "8090:80"
    depends_on:
      backend:
        condition: service_started

volumes:
  mysql_data:
    name: mysql_data

networks:
  default:
    name: my_network
